sudo: required
language: node_js
services:
  - docker

before_install:
  - docker build -t apkap83/udemy_8910_react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true apkap83/udemy_8910_react-test npm test

after_success:
  - docker build -t apkap83/udemy_8910_client ./client
  - docker build -t apkap83/udemy_8910_nginx ./nginx
  - docker build -t apkap83/udemy_8910_server ./server
  - docker build -t apkap83/udemy_8910_worker ./worker

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take those images and push them to docker hub
  - docker push apkap83/udemy_8910_client
  - docker push apkap83/udemy_8910_nginx
  - docker push apkap83/udemy_8910_server
  - docker push apkap83/udemy_8910_worker
